### ISSUE TITLE
Error when build FolderOverlay for KML

### ISSUE THREAD

**Issue by JimBecker** [MKergall/osmbonuspack#119]
What steps will reproduce the problem?
1. Using Android Studio with OSMBonusPack v5.1 + osmdroid v4.3 as libraries;
2. Trying to parse kml-file and open it with bonuspack;
3. The kml-file loading is successful, but can't build FolderOverlay.

What is the expected output? What do you see instead?
I want to show KML on my OSM map.
I used the code as in Tutorial_4, but got a FATAL EXCEPTION when run :

Error: "No package identifier when getting value for resource number 0x00000000"

in this line:

FolderOverlay kmlOverlay = (FolderOverlay)kmlDocument.mKmlRoot.buildOverlay(map, defaultStyle, null, kmlDocument);
 	
When debugging shows that the KML is loaded and parsed successful, but can't build FolderOverlay.
			
When I use the OSMBonusPack v4.3 + osmdroid v4.1 with this code, it`s working.

What version of the products are you using (Android SDK, osmdroid,
OSMBonusPack)?
Android SDK: 8;
OSMDroid: 4.3;
OSMBonusPack: 5.1

Please provide any additional information below.

**Comment by MKergall** [comment]
Probably a configuration issue (missing jar like gson or commons-lang?). 
Please provide the full stack trace of the exception. 
Also, if you can debug, you could go inside buildOverlay and identify where is the issue exactly.

**Comment by Sushinn** [comment]
I've have the same problem, did you find a solution?
Here is my StackTrace:

06-04 20:08:52.945: W/ResourceType(9059): No package identifier when getting value for resource number 0x00000000
06-04 20:08:52.945: D/AndroidRuntime(9059): Shutting down VM
06-04 20:08:52.946: E/AndroidRuntime(9059): FATAL EXCEPTION: main
06-04 20:08:52.946: E/AndroidRuntime(9059): Process: com.granzotto.busdroid, PID: 9059
06-04 20:08:52.946: E/AndroidRuntime(9059): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.granzotto.busdroid/com.granzotto.busdroid.MapActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x0
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.app.ActivityThread.access$800(ActivityThread.java:148)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.os.Looper.loop(Looper.java:135)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.app.ActivityThread.main(ActivityThread.java:5312)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at java.lang.reflect.Method.invoke(Native Method)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at java.lang.reflect.Method.invoke(Method.java:372)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
06-04 20:08:52.946: E/AndroidRuntime(9059): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.content.res.Resources.getValue(Resources.java:1233)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2601)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.content.res.Resources.getLayout(Resources.java:1049)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:412)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at org.osmdroid.bonuspack.overlays.InfoWindow.<init>(InfoWindow.java:41)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at org.osmdroid.bonuspack.overlays.BasicInfoWindow.<init>(BasicInfoWindow.java:40)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at org.osmdroid.bonuspack.kml.KmlLineString.applyDefaultStyling(KmlLineString.java:54)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at org.osmdroid.bonuspack.kml.KmlLineString.buildOverlay(KmlLineString.java:71)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at org.osmdroid.bonuspack.kml.KmlPlacemark.buildOverlay(KmlPlacemark.java:118)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:160)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:160)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at com.granzotto.busdroid.MapActivity.onCreate(MapActivity.java:58)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.app.Activity.performCreate(Activity.java:5953)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
06-04 20:08:52.946: E/AndroidRuntime(9059): 	... 10 more

**Comment by Sushinn** [comment]
Fixed it!

I was missing the bubble files:
drawable-mpi/bonuspack_bubble.9.png
layout/bonuspack_bubble.xml
drawable-mpi/bonuspack_bubble_black.9.png
layout/bonuspack_bubble_black.xml
drawable/btn_moreinfo.xml
drawable-mpi/moreinfo_arrow.png
drawable-mpi/moreinfo_arrow_pressed.png
