### ISSUE TITLE
Gradle build error

### ISSUE THREAD

**Issue by AliKhaleghi76** [MKergall/osmbonuspack#267]
I've tried both gradle including methods but gradle can't sync. 
in first method I get gradle can't resolve dependency error and in second method i get failed to resolve: osmbonuspack_v6.0 error.
please help !

**Comment by MKergall** [comment]
Start with something working: the Tutorial project OSMBonusPack tuto.

**Comment by AliKhaleghi76** [comment]
@MKergall I've used tutorial and get the error!
As i found there are two method to add library:
1. Gradle dependency
2. Use aar file
I've tried both of them but in both of them gradle can't sync itself :(

**Comment by spyhunter99** [comment]
Great build system isn't it?

On Dec 8, 2016 2:48 PM, "AliKhaleghi76" <notifications@github.com> wrote:

@MKergall <https://github.com/MKergall> I've used tutorial and get the
error!
As i found there are two method to add library:

   1. Gradle dependency
   2. Use aar file
   I've tried both of them but in both of them gradle can't sync itself :(

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MKergall/osmbonuspack/issues/267#issuecomment-265836396>,
or mute the thread

**Comment by spyhunter99** [comment]
occasionally, the brilliant and heroic engineers at google republish artifacts, such as the gradle android plugin and various bits of the android support libraries and break stuff in the process. They usually fix it quickly, but this means that if you were unlucky enough to try and build during the time it was broken, you're locally cached stuff could be all kinds of out of whack and broken.

potential solution:
delete ~/.gradle/caches
delete projectHome/.gradle
then try the build again and hope for the best

**Comment by AliKhaleghi76** [comment]
@spyhunter99 Tnx, My Problem solved <3
