### ISSUE TITLE
Mapquest Roadmanager Return Issue

### ISSUE THREAD

**Issue by moprei** [MKergall/osmbonuspack#314]
i use the mapquest roadmanager to get all waypoints to draw a polyline with them (&routeType=pedestrian). I update the polyline every sec. my problem with the mapquest roadmanager is that i do not get consistent responses (i use async task). Refering to the Status Code 602 the roadmanager returns only the start and endpoint and it draws a straight line. In the next moment it totally works for me again (status code 0) route is drawn perfectly. but there are big time gaps in between, where i do not get more than these 2 points. is this a known issue, or what could i have done wrong?

**Comment by MKergall** [comment]
If you mean that you are requesting MapQuest routing service every second, then I'm not surprised: this is not a fair usage of this kind of service. And your route cannot change every second. 
Request only when you really need it (new destination requested by the user), and everything should be OK.

**Comment by moprei** [comment]
thanks for the fast answer. what do you recommend for this case then? isn't it a problem if the gps (my position is starting point in my navigation) is not accurate at the first request? it would draw my polyline false once and never be changed. 
i have been using google maps and thought requesting the API frequently was the most common way to draw the polyline between my position and my targets position. do you have any suggestions to keep the same functionality with your nice service?

**Comment by MKergall** [comment]
You perform your initial route request. 
Then, as long as your current position is reasonably "on this route", what is the need for a new request? Check if the best route changed due to traffic conditions? Would be relevant if we had traffic info - but we don't! 

So, request for a new route only when your position is "far" from the current route. 

Is you already tried Waze (I'm sure you did), this is exactly what they do - with a smart "beep" preventing the user that a new route has been computed.

**Comment by rachha** [comment]
@MKergall thanks for the info, how can I measure the distance from My Position to the current route.

**Comment by MKergall** [comment]
questions on StackOverflow please.
