### ISSUE TITLE
How to supprot<minLodPixels> to load different Placemark with different map zoom level

### ISSUE THREAD

**Issue by pwc1993** [MKergall/osmbonuspack#348]
when a <placemark> in kml has the label like:
<Lod>
	<minLodPixels>64</minLodPixels>
	<maxLodPixels>1e+008</maxLodPixels>
	<minFadeExtent>0</minFadeExtent>
	<maxFadeExtent>0</maxFadeExtent>
</Lod>
it can control when to show the placemark with the zoom level,what is it looks like in google earth :
![image](https://user-images.githubusercontent.com/19483970/47004793-e7c23780-d164-11e8-8c45-fb33562731a9.png)
![image](https://user-images.githubusercontent.com/19483970/47004818-f14b9f80-d164-11e8-8442-d46645ec2222.png)
now ,when add kml to the map ,it will show all feature at the same time
![image](https://user-images.githubusercontent.com/19483970/47004996-64551600-d165-11e8-9f8b-c3a16b082477.png)

**Comment by pwc1993** [comment]
"  <Lod>
					<minLodPixels>64</minLodPixels>
					<maxLodPixels>1e+008</maxLodPixels>
					<minFadeExtent>0</minFadeExtent>
					<maxFadeExtent>0</maxFadeExtent>
				</Lod>"

**Comment by pwc1993** [comment]
![image](https://user-images.githubusercontent.com/19483970/47005126-b26a1980-d165-11e8-902b-46dd50992ef3.png)

**Comment by MKergall** [comment]
Lod is a property of Regions. 
[KML Region](https://developers.google.com/kml/documentation/regions) is a very interesting concept, but far beyond OSMBonusPack capabilities. 

In addition, Region targets optimized drawing of large datasets. But, due to contraints on memory, large KML datasets are not easily reachable on Android - this would require a complete rework of OSMBonusPack KML mechanisms.

**Comment by pwc1993** [comment]
thanks a lot
